# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_hoard_global_optspecs
	string join \n h/help V/version
end

function __fish_hoard_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_hoard_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_hoard_using_subcommand
	set -l cmd (__fish_hoard_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c hoard -n "__fish_hoard_needs_command" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_needs_command" -s V -l version -d 'Print version'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "add" -d 'Add a tool to the database'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "show" -d 'Show a specific tool\'s details'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "remove" -d 'Remove a tool from the database'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "edit" -d 'Edit a tool\'s metadata interactively'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "sync" -d 'Sync database with system state'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "discover" -d 'Discover and explore tools'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "insights" -d 'View usage analytics and system health'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "ai" -d 'AI-powered tool management'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "init" -d 'First-time setup wizard'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "maintain" -d 'Daily/weekly maintenance routine'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "cleanup" -d 'Cleanup wizard for unused tools and issues'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "install" -d 'Install a tool'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "uninstall" -d 'Uninstall a tool'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "upgrade" -d 'Upgrade a tool (update or switch sources)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "updates" -d 'Check for available updates'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "bundle" -d 'Manage tool bundles'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "config" -d 'Manage dotfiles and tool configurations'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "export" -d 'Export tools database to a file'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "import" -d 'Import tools from a file'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "gh" -d 'GitHub integration (advanced)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "completions" -d 'Generate shell completions'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "list" -d 'List tools in the database'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "search" -d 'Search tools by name or description'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "scan" -d 'Scan system for installed tools (use \'sync --scan\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "fetch-descriptions" -d 'Fetch missing descriptions (use \'sync --descriptions\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "suggest" -d 'Show suggestions (use \'discover missing\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "stats" -d 'Show database statistics (use \'insights stats\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "info" -d 'Show database file location (use \'insights stats\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "categories" -d 'List all categories (use \'discover categories\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "labels" -d 'List all labels (use \'discover labels\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "usage" -d 'Track and show tool usage (use \'insights usage\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "unused" -d 'Find unused tools (use \'insights unused\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "recommend" -d 'Get recommendations (use \'discover recommended\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "doctor" -d 'Check database health (use \'insights health\' instead)'
complete -c hoard -n "__fish_hoard_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand add" -s d -l description -d 'Description of the tool' -r
complete -c hoard -n "__fish_hoard_using_subcommand add" -s c -l category -d 'Category (e.g., search, files, git)' -r
complete -c hoard -n "__fish_hoard_using_subcommand add" -s s -l source -d 'Installation source (cargo, apt, snap, npm, pip, manual)' -r
complete -c hoard -n "__fish_hoard_using_subcommand add" -s i -l install-cmd -d 'Install command' -r
complete -c hoard -n "__fish_hoard_using_subcommand add" -s b -l binary -d 'Binary name (if different from tool name)' -r
complete -c hoard -n "__fish_hoard_using_subcommand add" -l installed -d 'Mark as installed'
complete -c hoard -n "__fish_hoard_using_subcommand add" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand show" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand remove" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand remove" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand edit" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -l limit -d 'Maximum tools to process for GitHub sync' -r
complete -c hoard -n "__fish_hoard_using_subcommand sync" -l delay -d 'Delay between GitHub API calls in ms (default: 2000)' -r
complete -c hoard -n "__fish_hoard_using_subcommand sync" -s d -l dry-run -d 'Only show what would change (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -l scan -d 'Also scan system for new tools'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -l github -d 'Also sync GitHub data (stars, topics, descriptions)'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -l usage -d 'Also scan shell history for usage data'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -l descriptions -d 'Also fetch missing descriptions from registries'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -s a -l all -d 'Perform all sync operations (scan + github + usage + descriptions)'
complete -c hoard -n "__fish_hoard_using_subcommand sync" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "list" -d 'List tools in the database'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "search" -d 'Search tools by name or description'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "categories" -d 'Browse tools by category'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "labels" -d 'Browse tools by label'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "missing" -d 'Find tools you don\'t have from our curated list'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "recommended" -d 'Get AI-powered recommendations based on your usage'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "similar" -d 'Find tools similar to one you already use'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "trending" -d 'Show trending tools by GitHub stars'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and not __fish_seen_subcommand_from list search categories labels missing recommended similar trending help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from list" -s c -l category -d 'Filter by category' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from list" -s L -l label -d 'Filter by label' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from list" -s f -l format -d 'Output format (table, json)' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from list" -s i -l installed -d 'Show only installed tools'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from search" -s l -l limit -d 'Maximum results for GitHub search' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from search" -l github -d 'Also search GitHub'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from categories" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from labels" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from missing" -s c -l category -d 'Filter by category' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from missing" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from recommended" -s c -l count -d 'Number of recommendations to show' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from recommended" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from similar" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from trending" -s c -l category -d 'Filter by category' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from trending" -s l -l limit -d 'Number of tools to show' -r
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from trending" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "list" -d 'List tools in the database'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "search" -d 'Search tools by name or description'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "categories" -d 'Browse tools by category'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "labels" -d 'Browse tools by label'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "missing" -d 'Find tools you don\'t have from our curated list'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "recommended" -d 'Get AI-powered recommendations based on your usage'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "similar" -d 'Find tools similar to one you already use'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "trending" -d 'Show trending tools by GitHub stars'
complete -c hoard -n "__fish_hoard_using_subcommand discover; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -f -a "usage" -d 'Show usage statistics'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -f -a "unused" -d 'Find installed tools you never use'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -f -a "health" -d 'Check database health and find issues'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -f -a "stats" -d 'Show database statistics'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -f -a "overview" -d 'Show combined overview dashboard'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and not __fish_seen_subcommand_from usage unused health stats overview help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from usage" -s l -l limit -d 'Number of top tools to show' -r
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from usage" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from unused" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from health" -s f -l fix -d 'Automatically fix issues where possible'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from health" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from stats" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from overview" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from help" -f -a "usage" -d 'Show usage statistics'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from help" -f -a "unused" -d 'Find installed tools you never use'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from help" -f -a "health" -d 'Check database health and find issues'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from help" -f -a "stats" -d 'Show database statistics'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from help" -f -a "overview" -d 'Show combined overview dashboard'
complete -c hoard -n "__fish_hoard_using_subcommand insights; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "config" -d 'Configure AI provider'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "enrich" -d 'Enrich tool data using AI'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "suggest-bundle" -d 'Suggest tool bundles based on your installed tools'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "set" -d 'Set the AI provider (use \'ai config set\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "show" -d 'Show current AI configuration (use \'ai config show\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "test" -d 'Test AI connection (use \'ai config test\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "categorize" -d 'Auto-categorize tools (use \'ai enrich --categorize\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "describe" -d 'Generate descriptions (use \'ai enrich --describe\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and not __fish_seen_subcommand_from config enrich suggest-bundle set show test categorize describe help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from config" -f -a "set" -d 'Set the AI provider to use'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from config" -f -a "show" -d 'Show current AI configuration'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from config" -f -a "test" -d 'Test AI connection'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from config" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from enrich" -s l -l limit -d 'Maximum number of tools to process' -r
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from enrich" -l categorize -d 'Categorize uncategorized tools'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from enrich" -l describe -d 'Generate descriptions for tools missing them'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from enrich" -s a -l all -d 'Do both categorize and describe'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from enrich" -s d -l dry-run -d 'Only show what would be changed (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from enrich" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from suggest-bundle" -s c -l count -d 'Number of bundle suggestions to generate' -r
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from suggest-bundle" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from test" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from categorize" -s d -l dry-run -d 'Only show what would be changed (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from categorize" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from describe" -s l -l limit -d 'Maximum number of tools to process' -r
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from describe" -s d -l dry-run -d 'Only show what would be changed (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from describe" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "config" -d 'Configure AI provider'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "enrich" -d 'Enrich tool data using AI'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "suggest-bundle" -d 'Suggest tool bundles based on your installed tools'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the AI provider (use \'ai config set\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show current AI configuration (use \'ai config show\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "test" -d 'Test AI connection (use \'ai config test\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "categorize" -d 'Auto-categorize tools (use \'ai enrich --categorize\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "describe" -d 'Generate descriptions (use \'ai enrich --describe\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand ai; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand init" -l auto -d 'Run non-interactively with defaults'
complete -c hoard -n "__fish_hoard_using_subcommand init" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c hoard -n "__fish_hoard_using_subcommand maintain" -l auto -d 'Run non-interactively'
complete -c hoard -n "__fish_hoard_using_subcommand maintain" -s d -l dry-run -d 'Only show what would be done'
complete -c hoard -n "__fish_hoard_using_subcommand maintain" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c hoard -n "__fish_hoard_using_subcommand cleanup" -s f -l force -d 'Skip confirmations'
complete -c hoard -n "__fish_hoard_using_subcommand cleanup" -s d -l dry-run -d 'Only show what would be done'
complete -c hoard -n "__fish_hoard_using_subcommand cleanup" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c hoard -n "__fish_hoard_using_subcommand install" -s s -l source -d 'Installation source (cargo, pip, npm, apt, brew, snap)' -r
complete -c hoard -n "__fish_hoard_using_subcommand install" -s V -l version -d 'Install a specific version' -r
complete -c hoard -n "__fish_hoard_using_subcommand install" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand install" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand uninstall" -s r -l remove -d 'Also remove from database'
complete -c hoard -n "__fish_hoard_using_subcommand uninstall" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand uninstall" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand upgrade" -s t -l to -d 'Switch to a different source (cargo, pip, npm, apt, brew)' -r
complete -c hoard -n "__fish_hoard_using_subcommand upgrade" -s V -l version -d 'Install a specific version' -r
complete -c hoard -n "__fish_hoard_using_subcommand upgrade" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand upgrade" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand updates" -s s -l source -d 'Filter by source (cargo, pip, npm, apt, brew)' -r
complete -c hoard -n "__fish_hoard_using_subcommand updates" -s x -l cross -d 'Check if apt/snap tools have newer versions on other sources'
complete -c hoard -n "__fish_hoard_using_subcommand updates" -s t -l tracked -d 'Only show updates for tools tracked in hoard database'
complete -c hoard -n "__fish_hoard_using_subcommand updates" -s a -l all-versions -d 'Show all available newer versions (not just latest)'
complete -c hoard -n "__fish_hoard_using_subcommand updates" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "create" -d 'Create a new bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "list" -d 'List all bundles'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "show" -d 'Show tools in a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "install" -d 'Install all tools in a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "add" -d 'Add tools to an existing bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "remove" -d 'Remove tools from a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "delete" -d 'Delete a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "update" -d 'Update tools in a bundle (interactive per-tool choices)'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and not __fish_seen_subcommand_from create list show install add remove delete update help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from create" -s d -l description -d 'Bundle description' -r
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from install" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from delete" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from update" -s y -l yes -d 'Auto-update all to latest without prompting'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from update" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "create" -d 'Create a new bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all bundles'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show tools in a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "install" -d 'Install all tools in a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "add" -d 'Add tools to an existing bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove tools from a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "update" -d 'Update tools in a bundle (interactive per-tool choices)'
complete -c hoard -n "__fish_hoard_using_subcommand bundle; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "link" -d 'Link a config directory to be managed by hoard'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "unlink" -d 'Unlink a config (removes from database, optionally removes symlink)'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "list" -d 'List all managed configs'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "show" -d 'Show details for a specific config'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "sync" -d 'Create symlinks for all managed configs'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "status" -d 'Check status of all config symlinks'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "edit" -d 'Edit a config\'s paths'
complete -c hoard -n "__fish_hoard_using_subcommand config; and not __fish_seen_subcommand_from link unlink list show sync status edit help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from link" -s t -l tool -d 'Associate with a tool' -r
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from link" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from unlink" -s r -l remove-symlink -d 'Also remove the symlink'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from unlink" -s f -l force -d 'Skip confirmation'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from unlink" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from list" -s f -l format -d 'Output format (table, json)' -r
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from list" -s b -l broken -d 'Show only configs with broken symlinks'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from sync" -s d -l dry-run -d 'Only show what would be done (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from sync" -s f -l force -d 'Force overwrite existing files (not symlinks)'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from edit" -s t -l target -d 'New target path' -r
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from edit" -s s -l source -d 'New source path' -r
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from edit" -l tool -d 'Associate with a tool' -r
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "link" -d 'Link a config directory to be managed by hoard'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "unlink" -d 'Unlink a config (removes from database, optionally removes symlink)'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all managed configs'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show details for a specific config'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Create symlinks for all managed configs'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "status" -d 'Check status of all config symlinks'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "edit" -d 'Edit a config\'s paths'
complete -c hoard -n "__fish_hoard_using_subcommand config; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand export" -s o -l output -d 'Output file path (supports .json or .toml)' -r
complete -c hoard -n "__fish_hoard_using_subcommand export" -s f -l format -d 'Export format (json or toml)' -r
complete -c hoard -n "__fish_hoard_using_subcommand export" -s i -l installed -d 'Only export installed tools'
complete -c hoard -n "__fish_hoard_using_subcommand export" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand import" -s s -l skip-existing -d 'Skip tools that already exist'
complete -c hoard -n "__fish_hoard_using_subcommand import" -s d -l dry-run -d 'Only show what would be imported (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand import" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "sync" -d 'Sync tools with GitHub (use \'sync --github\' instead for most cases)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "rate-limit" -d 'Show GitHub API rate limit status'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "backfill" -d 'Backfill missing descriptions from cached GitHub data (no API calls)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "fetch" -d 'Fetch GitHub info for a specific tool'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "search" -d 'Search GitHub for a tool'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "info" -d 'Show GitHub info for a tool'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and not __fish_seen_subcommand_from sync rate-limit backfill fetch search info help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from sync" -s l -l limit -d 'Maximum number of tools to process' -r
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from sync" -l delay -d 'Delay between API calls in milliseconds' -r
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from sync" -s d -l dry-run -d 'Only show what would be changed (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from sync" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from rate-limit" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from backfill" -s d -l dry-run -d 'Only show what would be changed (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from backfill" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from fetch" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from search" -s l -l limit -d 'Maximum results' -r
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "sync" -d 'Sync tools with GitHub (use \'sync --github\' instead for most cases)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "rate-limit" -d 'Show GitHub API rate limit status'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "backfill" -d 'Backfill missing descriptions from cached GitHub data (no API calls)'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "fetch" -d 'Fetch GitHub info for a specific tool'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "search" -d 'Search GitHub for a tool'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "info" -d 'Show GitHub info for a tool'
complete -c hoard -n "__fish_hoard_using_subcommand gh; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand completions" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand list" -s c -l category -d 'Filter by category' -r
complete -c hoard -n "__fish_hoard_using_subcommand list" -s L -l label -d 'Filter by label' -r
complete -c hoard -n "__fish_hoard_using_subcommand list" -s f -l format -d 'Output format (table, json)' -r
complete -c hoard -n "__fish_hoard_using_subcommand list" -s i -l installed -d 'Show only installed tools'
complete -c hoard -n "__fish_hoard_using_subcommand list" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand search" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand scan" -s d -l dry-run -d 'Only show what would be added (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand scan" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand fetch-descriptions" -s d -l dry-run -d 'Only show what would be updated (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand fetch-descriptions" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand suggest" -s c -l category -d 'Filter by category' -r
complete -c hoard -n "__fish_hoard_using_subcommand suggest" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand stats" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand info" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand categories" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand labels" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and not __fish_seen_subcommand_from scan show tool help" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and not __fish_seen_subcommand_from scan show tool help" -f -a "scan" -d 'Scan shell history and update usage counts'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and not __fish_seen_subcommand_from scan show tool help" -f -a "show" -d 'Show usage statistics'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and not __fish_seen_subcommand_from scan show tool help" -f -a "tool" -d 'Show usage for a specific tool'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and not __fish_seen_subcommand_from scan show tool help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from scan" -s d -l dry-run -d 'Only show what would be recorded (dry run)'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from scan" -l reset -d 'Reset usage counts before scanning'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from scan" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from show" -s l -l limit -d 'Number of top tools to show' -r
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from tool" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from help" -f -a "scan" -d 'Scan shell history and update usage counts'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show usage statistics'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from help" -f -a "tool" -d 'Show usage for a specific tool'
complete -c hoard -n "__fish_hoard_using_subcommand usage; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand unused" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand recommend" -s c -l count -d 'Number of recommendations to show' -r
complete -c hoard -n "__fish_hoard_using_subcommand recommend" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand doctor" -s f -l fix -d 'Automatically fix issues where possible'
complete -c hoard -n "__fish_hoard_using_subcommand doctor" -s h -l help -d 'Print help'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "add" -d 'Add a tool to the database'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "show" -d 'Show a specific tool\'s details'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "remove" -d 'Remove a tool from the database'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "edit" -d 'Edit a tool\'s metadata interactively'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "sync" -d 'Sync database with system state'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "discover" -d 'Discover and explore tools'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "insights" -d 'View usage analytics and system health'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "ai" -d 'AI-powered tool management'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "init" -d 'First-time setup wizard'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "maintain" -d 'Daily/weekly maintenance routine'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "cleanup" -d 'Cleanup wizard for unused tools and issues'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "install" -d 'Install a tool'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "uninstall" -d 'Uninstall a tool'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "upgrade" -d 'Upgrade a tool (update or switch sources)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "updates" -d 'Check for available updates'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "bundle" -d 'Manage tool bundles'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "config" -d 'Manage dotfiles and tool configurations'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "export" -d 'Export tools database to a file'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "import" -d 'Import tools from a file'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "gh" -d 'GitHub integration (advanced)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "completions" -d 'Generate shell completions'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "list" -d 'List tools in the database'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "search" -d 'Search tools by name or description'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "scan" -d 'Scan system for installed tools (use \'sync --scan\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "fetch-descriptions" -d 'Fetch missing descriptions (use \'sync --descriptions\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "suggest" -d 'Show suggestions (use \'discover missing\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "stats" -d 'Show database statistics (use \'insights stats\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "info" -d 'Show database file location (use \'insights stats\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "categories" -d 'List all categories (use \'discover categories\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "labels" -d 'List all labels (use \'discover labels\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "usage" -d 'Track and show tool usage (use \'insights usage\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "unused" -d 'Find unused tools (use \'insights unused\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "recommend" -d 'Get recommendations (use \'discover recommended\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "doctor" -d 'Check database health (use \'insights health\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and not __fish_seen_subcommand_from add show remove edit sync discover insights ai init maintain cleanup install uninstall upgrade updates bundle config export import gh completions list search scan fetch-descriptions suggest stats info categories labels usage unused recommend doctor help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "list" -d 'List tools in the database'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "search" -d 'Search tools by name or description'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "categories" -d 'Browse tools by category'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "labels" -d 'Browse tools by label'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "missing" -d 'Find tools you don\'t have from our curated list'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "recommended" -d 'Get AI-powered recommendations based on your usage'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "similar" -d 'Find tools similar to one you already use'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from discover" -f -a "trending" -d 'Show trending tools by GitHub stars'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from insights" -f -a "usage" -d 'Show usage statistics'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from insights" -f -a "unused" -d 'Find installed tools you never use'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from insights" -f -a "health" -d 'Check database health and find issues'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from insights" -f -a "stats" -d 'Show database statistics'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from insights" -f -a "overview" -d 'Show combined overview dashboard'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "config" -d 'Configure AI provider'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "enrich" -d 'Enrich tool data using AI'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "suggest-bundle" -d 'Suggest tool bundles based on your installed tools'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "set" -d 'Set the AI provider (use \'ai config set\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "show" -d 'Show current AI configuration (use \'ai config show\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "test" -d 'Test AI connection (use \'ai config test\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "categorize" -d 'Auto-categorize tools (use \'ai enrich --categorize\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from ai" -f -a "describe" -d 'Generate descriptions (use \'ai enrich --describe\' instead)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "create" -d 'Create a new bundle'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "list" -d 'List all bundles'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "show" -d 'Show tools in a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "install" -d 'Install all tools in a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "add" -d 'Add tools to an existing bundle'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "remove" -d 'Remove tools from a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "delete" -d 'Delete a bundle'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from bundle" -f -a "update" -d 'Update tools in a bundle (interactive per-tool choices)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "link" -d 'Link a config directory to be managed by hoard'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "unlink" -d 'Unlink a config (removes from database, optionally removes symlink)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "list" -d 'List all managed configs'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "show" -d 'Show details for a specific config'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "sync" -d 'Create symlinks for all managed configs'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "status" -d 'Check status of all config symlinks'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from config" -f -a "edit" -d 'Edit a config\'s paths'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from gh" -f -a "sync" -d 'Sync tools with GitHub (use \'sync --github\' instead for most cases)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from gh" -f -a "rate-limit" -d 'Show GitHub API rate limit status'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from gh" -f -a "backfill" -d 'Backfill missing descriptions from cached GitHub data (no API calls)'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from gh" -f -a "fetch" -d 'Fetch GitHub info for a specific tool'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from gh" -f -a "search" -d 'Search GitHub for a tool'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from gh" -f -a "info" -d 'Show GitHub info for a tool'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from usage" -f -a "scan" -d 'Scan shell history and update usage counts'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from usage" -f -a "show" -d 'Show usage statistics'
complete -c hoard -n "__fish_hoard_using_subcommand help; and __fish_seen_subcommand_from usage" -f -a "tool" -d 'Show usage for a specific tool'
